config/routes.rb
Hex::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"  
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :socket_gems
  resources :champions
  resources :items
  resources :gear
  resources :pages
  resources :releases
  resources :traits
  resources :cards
  resources :users
  resources :sessions
  
  match '/links' => 'pages#show', :id => '2', :as => 'links'
  match '/cardexport' => 'cards#export'
  match '/itemexport' => 'items#export'
       

   root :to => 'pages#show', :id => '1'

end

app/models/card.rb
class Card < ActiveRecord::Base
#  COLOR = { "Artifact" => 0, "Blood" => 1, "Wild" => 2, "Diamond" => 3, "Ruby" => 4, "Sapphire" => 5 }
#  FACTION = { "None" => 0, "Ardent" => 1, "Underworld" => 2 }
#  RESTRICTION = { "None" => 0, "Unique" => 1 }
#  RARITY = { "None" => 0, "Common" => 1, "Uncommon" => 2, "Rare" => 3, "Legendary - PvE" => 4, "Legendary - PvP" => 5}
#  CARD_TYPE = { "Resource" => 0, "Constant" => 1, "Troop" => 2, "Basic Action" => 3, "Quick Action" => 4, "Artifact" => 5, "Artifact Troop" => 6}

#  def color
#    COLOR.key(read_attribute(:color))
#  end

#  def faction
#    FACTION.key(read_attribute(:faction))
#  end

#  def restriction
#    RESTRICTION.key(read_attribute(:restriction))
#  end

#  def rarity
#    RARITY.key(read_attribute(:rarity))
#  end

#  def card_type
#    CARD_TYPE.key(read_attribute(:card_type))
#  end
  
  def name_with_initial
    "#{name}"
  end

  def self.search(search)
    if search
      where('name LIKE ? OR traits LIKE ? OR game_text LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
  
  
  has_many :item
  belongs_to :release
  attr_accessible :related_card_id, :related_card2_id, :related_card3_id, :related_card4_id, :traits, :attack, :color, :cost, :defense, :faction, :game_text, :lore_text, :name, :number, :pve, :rarity, :restriction, :release_id, :threshold, :card_type, :image_main, :image_back, :image_alt_1
end

app/models/champion.rb
class Champion < ActiveRecord::Base
  POWER_TYPE = { "None" => 0, "Charge Power" => 1, "Passive Power" => 2, "Special Card" => 3, "Start of Game" => 4 }
  def power1_type
    POWER_TYPE.key(read_attribute(:power1_type))
  end
  def power2_type
    POWER_TYPE.key(read_attribute(:power2_type))
  end
  def power3_type
    POWER_TYPE.key(read_attribute(:power3_type))
  end
  def power4_type
    POWER_TYPE.key(read_attribute(:power4_type))
  end

  attr_accessible :name, :power1_game_text, :power1_name, :power1_type, :power1_unlock, :power2_game_text, :power2_name, :power2_type, :power2_unlock, :power3_game_text, :power3_name, :power3_type, :power3_unlock, :power4_game_text, :power4_name, :power4_type, :power4_unlock, :image_main, :source
end

app/models/item.rb
class Item < ActiveRecord::Base
  ITEM_TYPE = { "None" => 0, "Helmet" => 1, "Armor" => 2, "Glove" => 3, "Boots" => 4, "Weapon" => 5, "Trinket" => 6 }  
  RARITY = { "None" => 0, "Common" => 1, "Uncommon" => 2, "Rare" => 3, "Legendary" => 4}
  
 # def item_type
#    ITEM_TYPE.key(read_attribute(:item_type))
#  end
  def rarity
    RARITY.key(read_attribute(:rarity))
  end  

  def self.search(search)
    if search
      where('item_name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
      
  belongs_to :card
  attr_accessible :card_id, :game_text, :image_main, :item_type, :lore_text, :item_name, :rarity, :rulings, :set_card_id, :source
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description, :name, :rank, :url
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/release.rb
class Release < ActiveRecord::Base
  validates_uniqueness_of :release_name, :short_name
  
  def name_with_initial
    "#{release_name}"
  end

  has_many :card
  
  attr_accessible :release_name, :short_name, :release_date, :size
end

app/models/socket_gem.rb
class SocketGem < ActiveRecord::Base
  
  def name_with_initial
    "#{name}"
  end
    
      
  attr_accessible :gem_color, :game_text, :gem_name, :gem_type
end

app/models/trait.rb
class Trait < ActiveRecord::Base
  
  validates_uniqueness_of :trait_name
  
  def name_with_initial
    "#{trait_name}"
  end

  attr_accessible :trait_name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :email, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/controllers/socket_gems_controller.rb
class SocketGemsController < ApplicationController
  # GET /socket_gems
  # GET /socket_gems.json
  def index
    @socket_gems = SocketGem.order("gem_name asc")
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @socket_gems }
    end
  end

  # GET /socket_gems/1
  # GET /socket_gems/1.json
  def show
    @socket_gem = SocketGem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @socket_gem }
    end
  end

  # GET /socket_gems/new
  # GET /socket_gems/new.json
  def new
  if current_user  
    @socket_gem = SocketGem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @socket_gem }
    end
  else
  redirect_to root_url
end     
  end

  # GET /socket_gems/1/edit
  def edit
    if current_user
    @socket_gem = SocketGem.find(params[:id])
      else
      redirect_to root_url
    end      
  end

  # POST /socket_gems
  # POST /socket_gems.json
  def create
    @socket_gem = SocketGem.new(params[:socket_gem])

    respond_to do |format|
      if @socket_gem.save
        format.html { redirect_to @socket_gem, notice: 'Socket gem was successfully created.' }
        format.json { render json: @socket_gem, status: :created, location: @socket_gem }
      else
        format.html { render action: "new" }
        format.json { render json: @socket_gem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /socket_gems/1
  # PUT /socket_gems/1.json
  def update
    @socket_gem = SocketGem.find(params[:id])

    respond_to do |format|
      if @socket_gem.update_attributes(params[:socket_gem])
        format.html { redirect_to @socket_gem, notice: 'Socket gem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @socket_gem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /socket_gems/1
  # DELETE /socket_gems/1.json
#  def destroy
#    @socket_gem = SocketGem.find(params[:id])
#    @socket_gem.destroy

#    respond_to do |format|
#      format.html { redirect_to socket_gems_url }
#      format.json { head :no_content }
#    end
#  end
end

app/helpers/card_types_helper.rb
module CardTypesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/socket_gems_helper.rb
module SocketGemsHelper
end

app/helpers/traits_helper.rb
module TraitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/socket_gems/_form.html.erb
<%= form_for(@socket_gem) do |f| %>
  <% if @socket_gem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@socket_gem.errors.count, "error") %> prohibited this socket_gem from being saved:</h2>

      <ul>
      <% @socket_gem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gem_name %><br />
    <%= f.text_field :gem_name %>
  </div>
  <div class="field">
    <%= f.label :gem_color %><br />
	<%= f.select :gem_color, {"Artifact" => "Artifact", "Blood" => "Blood", "Wild" => "Wild", "Diamond" => "Diamond", "Ruby" => "Ruby", "Sapphire" => "Sapphire"}%>
  </div>
  <div class="field">
    <%= f.label :gem_type %><br />
	<%= f.select :gem_type, {"Minor" => "Minor", "Major" => "Major"}%>
  </div>
  <div class="field">
    <%= f.label :game_text %><br />
    <%= f.text_area :game_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/socket_gems/edit.html.erb
<h1>Editing socket_gem</h1>

<%= render 'form' %>

<%= link_to 'Show', @socket_gem %> |
<%= link_to 'Back', socket_gems_path %>

app/views/socket_gems/index.html.erb
<% if current_user %>
<%= link_to 'New Socket gem', new_socket_gem_path %>
<% end %>


<h1>GEMS</h1>
<table width="980" class="pretty">
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Type</th>
    <th>Game text</th>
  </tr>

<% @socket_gems.each do |socket_gem| %>
  <tr class="<%= cycle("odd", "even") %>">	  
    <td><%= socket_gem.gem_name %></td>
    <td><%= socket_gem.gem_color %></td>
    <td><%= socket_gem.gem_type %></td>
    <td><%= socket_gem.game_text %></td>
  </tr>
<% end %>
</table>

<br />

app/views/socket_gems/new.html.erb
<h1>New socket_gem</h1>

<%= render 'form' %>

<%= link_to 'Back', socket_gems_path %>

app/views/socket_gems/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
<%= link_to 'Edit', edit_socket_gem_path(@socket_gem) %> |
<%= link_to 'New Socket gem', new_socket_gem_path %>
<% end %>

<p>
  <b>Name:</b>
  <%= @socket_gem.gem_name %>
</p>

<p>
  <b>Color:</b>
  <%= @socket_gem.gem_color %>
</p>

<p>
  <b>Type:</b>
  <%= @socket_gem.gem_type %>
</p>

<p>
  <b>Game text:</b>
  <%= @socket_gem.game_text %>
</p>