config/routes.rb
Hex::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"  
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :socket_gems
  resources :champions
  resources :items
  resources :gear
  resources :pages
  resources :releases
  resources :traits
  resources :cards
  resources :users
  resources :sessions
  
  match '/links' => 'pages#show', :id => '2', :as => 'links'
  match '/cardexport' => 'cards#export'
  match '/itemexport' => 'items#export'
       

   root :to => 'pages#show', :id => '1'

end

app/models/card.rb
class Card < ActiveRecord::Base
#  COLOR = { "Artifact" => 0, "Blood" => 1, "Wild" => 2, "Diamond" => 3, "Ruby" => 4, "Sapphire" => 5 }
#  FACTION = { "None" => 0, "Ardent" => 1, "Underworld" => 2 }
#  RESTRICTION = { "None" => 0, "Unique" => 1 }
#  RARITY = { "None" => 0, "Common" => 1, "Uncommon" => 2, "Rare" => 3, "Legendary - PvE" => 4, "Legendary - PvP" => 5}
#  CARD_TYPE = { "Resource" => 0, "Constant" => 1, "Troop" => 2, "Basic Action" => 3, "Quick Action" => 4, "Artifact" => 5, "Artifact Troop" => 6}

#  def color
#    COLOR.key(read_attribute(:color))
#  end

#  def faction
#    FACTION.key(read_attribute(:faction))
#  end

#  def restriction
#    RESTRICTION.key(read_attribute(:restriction))
#  end

#  def rarity
#    RARITY.key(read_attribute(:rarity))
#  end

#  def card_type
#    CARD_TYPE.key(read_attribute(:card_type))
#  end
  
  def name_with_initial
    "#{name}"
  end

  def self.search(search)
    if search
      where('name LIKE ? OR traits LIKE ? OR game_text LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
  
  
  has_many :item
  belongs_to :release
  attr_accessible :related_card_id, :related_card2_id, :related_card3_id, :related_card4_id, :traits, :attack, :color, :cost, :defense, :faction, :game_text, :lore_text, :name, :number, :pve, :rarity, :restriction, :release_id, :threshold, :card_type, :image_main, :image_back, :image_alt_1
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  helper_method :sort_column, :sort_direction


  # GET /cards
  # GET /cards.json
  def index
      @cards = Card.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 50, :page => params[:page])

      if params[:color] && params[:color] != "0"
        @cards = @cards.where("color = ?", params[:color])
      end
      if params[:card_type] && params[:card_type] != "0"
        @cards = @cards.where("card_type = ?", params[:card_type])
      end      

  end
  
  def export

    @cards = Card.all
   
    render :layout => false
    
  end
  

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])
    
    if @card.related_card_id
      @related = Card.find(@card.related_card_id)  
    else
      @related = nil
    end
    if @card.related_card2_id
      @related2 = Card.find(@card.related_card2_id)  
    else
      @related2 = nil
    end
    if @card.related_card3_id
      @related3 = Card.find(@card.related_card3_id)  
    else
      @related3 = nil
    end
    if @card.related_card4_id
      @related4 = Card.find(@card.related_card4_id)  
    else
      @related4 = nil
    end

        
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end
  

  # GET /cards/new
  # GET /cards/new.json
  def new
    if current_user
      @card = Card.new
      
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @card }
      end
    else
      redirect_to root_url
    end   
  end

  # GET /cards/1/edit
  def edit
    if current_user
      @card = Card.find(params[:id])
    else
      redirect_to root_url
    end
    
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])
    
    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
#  def destroy
#    @card = Card.find(params[:id])
#    @card.destroy

#    respond_to do |format|
#      format.html { redirect_to cards_url }
#      format.json { head :no_content }
#    end
#  end
  

    
  def sort_column
    Card.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end  
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_cards.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<%= will_paginate @cards %>

<table width="980" class="pretty">
  <tr>
    <th><%= sortable "name" %></th>
    <th><%= sortable "cost" %></th>
    <th><%= sortable "threshold", "Thr" %></th>
    <th><%= sortable "color" %></th>
    <th><%= sortable "card_type", "Type" %></th>
    <th><%= sortable "traits" %></th>
    <th><%= sortable "faction" %></th>
    <th><%= sortable "attack", "ATK" %></th>
    <th><%= sortable "defense", "DEF" %></th>
    <th><%= sortable "rarity" %></th>
    <th><%= sortable "pve", "PvE" %></th>	
  </tr>

  
<% for card in @cards %>
  <tr class="<%= cycle("odd", "even") %>">	  
    <td><%= link_to card.name, card %></td>
    <td><%= card.cost %></td>
    <td><%= card.threshold %></td>
    <td><%= card.color %></td>
    <td><%= card.card_type %></td>
    <td><%= card.traits %></td>
    <td><%= card.faction %></td>
    <td><%= card.attack %></td>
    <td><%= card.defense %></td>
    <td><%= card.rarity %></td>
    <td><%= card.pve %></td>	
  </tr>
<% end %>
</table>

<%= will_paginate @cards %>

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% if @card.image_main %>  
<%= image_tag(@card.image_main, :align=> "right") %>
<% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
    <%= f.label :threshold %>
    <%= f.number_field :threshold %>
  </div>
  <div class="field">
    <%= f.label :color %>
	<%= f.select :color, {"Colorless" => "Colorless", "Blood" => "Blood", "Wild" => "Wild", "Diamond" => "Diamond", "Ruby" => "Ruby", "Sapphire" => "Sapphire"}%>
    <%= f.label :card_type %>
    <%= f.select :card_type, { "Resource" => "Resource", "Constant" => "Constant", "Troop" => "Troop", "Basic Action" => "Basic Action", "Quick Action" => "Quick Action", "Artifact" => "Artifact", "Troop, Artifact" => "Troop, Artifact"} %>
  </div>
  <div class="field">
    <%= f.label :traits %>
	<%= collection_select(:card, :traits, Trait.order('trait_name ASC'), :trait_name, :name_with_initial, :prompt => true)%>
    <%= f.label :restriction %>
	<%= f.select :restriction, {"None" => "None", "Unique" => "Unique"}, :include_blank => true%>
    <%= f.label :faction %>
	<%= f.select :faction, {"None" => "None", "Ardent" => "Ardent", "Underworld" => "Underworld"}, :include_blank => true%>
  </div>
  <div class="field">
    <%= f.label :game_text %><br />
    <%= f.text_area :game_text, :size => "80x5" %>
  </div>
  <div class="field">
    <%= f.label :lore_text %><br />
    <%= f.text_area :lore_text, :size => "80x5" %>
  </div>
  <div class="field">
    <%= f.label :attack %>
    <%= f.number_field :attack %>
    <%= f.label :defense %>
    <%= f.number_field :defense %>
  </div>
  <div class="field">
    <%= f.label :release_id %>
    <%= collection_select(:card, :release_id, Release.order('release_date ASC'), :id, :name_with_initial, :prompt => true)%>
    <%= f.label :rarity %>
    <%= f.select :rarity, { "Token" => "Token", "Common" => "Common", "Uncommon" => "Uncommon", "Rare" => "Rare", "Legendary" => "Legendary"}, :include_blank => true %>
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :pve %><br />
	<%= f.select :pve, {"false" => "false", "true" => "true"} %>	
  </div>
  <div class="field">
    <%= f.label :related_card_id %><br />
	<%= collection_select(:card, :related_card_id, Card.order('name ASC'), :id, :name_with_initial, :prompt => true, :include_blank => true)%>	
  </div>  
  <div class="field">
    <%= f.label :related_card2_id %><br />
	<%= collection_select(:card, :related_card2_id, Card.order('name ASC'), :id, :name_with_initial, :prompt => true, :include_blank => true)%>	
  </div>  
  <div class="field">
    <%= f.label :related_card3_id %><br />
	<%= collection_select(:card, :related_card3_id, Card.order('name ASC'), :id, :name_with_initial, :prompt => true, :include_blank => true)%>	
  </div>  
  <div class="field">
    <%= f.label :related_card4_id %><br />
	<%= collection_select(:card, :related_card4_id, Card.order('name ASC'), :id, :name_with_initial, :prompt => true, :include_blank => true)%>	
  </div>  
        
  <div class="field">
    <%= f.label :image_main %>
    <%= f.text_field :image_main %>
  </div>
  <div class="field">
    <%= f.label :image_back %>
    <%= f.text_field :image_back %>
  </div>
  <div class="field">
    <%= f.label :image_alt_1 %>
    <%= f.text_field :image_alt_1 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

app/views/cards/export.html.erb
<% for card in @cards %>
<%= card.name +  "\t" + card.game_text + "\t" + card.lore_text + "\n\n"%>
<% end %> 

app/views/cards/index.html.erb
<% if current_user %>
<%= link_to 'New Card', new_card_path %>
<% end %>


<h1>CARDS</h1>

<%= form_tag cards_path, :method => 'get', :id => "cards_search" do %>
  <p>
    <%= text_field_tag :search, params[:search], :size => 40 %>
	<%= select_tag :color, options_for_select([["Color", "0"], "Colorless", "Blood", "Wild", "Diamond", "Ruby", "Sapphire"], :selected => params[:color])%>
    <%= select_tag :card_type, options_for_select([["Card Type", "0"], "Resource", "Troop", "Constant", "Basic Action", "Quick Action", "Artifact", "Artifact Troop"], :selected => params[:card_type])%>
	<%= submit_tag "Search", :name => nil %>
	<%= link_to 'reset', cards_path %>
  </p>
  <div id="cards"><%= render 'cards' %></div>
<% end %>
<br />
  <%= javascript_include_tag "card" %>

app/views/cards/index.js.erb
$("#cards").html("<%= escape_javascript(render("cards")) %>");

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'New Card', new_card_path %>
<% end %>

<div id="card-body">
	<div id="card-image">
<%= image_tag(@card.image_main) %>
	</div>
<div id="card-content">
<h1><%= @card.name %></h1>

<table>
<tr>
  <td align="right"><b>Cost:</b></td>
  <td><%= @card.cost %></td>
</tr>

<tr>
  <td align="right"><b>Threshold:</b></td>
  <td><%= @card.threshold %></td>
</tr>

<tr>
  <td align="right"><b>Color:</b></td>
  <td><%= @card.color %></td>
</tr>

<tr>
  <td align="right"><b>Type:</b></td>
  <td><%= @card.card_type %></td>
</tr>

<tr>
  <td align="right"><b>Traits:</b></td>
  <td><%= @card.traits %></td>
</p>

<tr>
  <td align="right"><b>Restriction:</b></td>
  <td><%= @card.restriction %></td>
</tr>

<tr>
  <td align="right"><b>Faction:</b></td>
  <td><%= @card.faction %></td>
</tr>

<tr>
  <td align="right"><b>Game text:</b></td>
  <td><%= @card.game_text %></td>
</tr>
<% if @card.lore_text != "" %>
<tr>
  <td align="right"><b>Lore text:</b></td>
  <td><%= @card.lore_text %></td>
</tr>
<% end %>
<tr>
  <td align="right"><b>Attack:</b></td>
  <td><%= @card.attack %></td>
</tr>

<tr>
  <td align="right"><b>Defense:</b></td>
  <td><%= @card.defense %></td>
</tr>

<tr>
  <td align="right"><b>Set:</b></td>
  <td><%= @card.release.release_name %></td>
</tr>

<tr>
  <td align="right"><b>Rarity:</b></td>
  <td><%= @card.rarity %></td>
</tr>

<tr>
  <td align="right"><b>Number:</b></td>
  <td><%= @card.number %></td>
</p>

<tr>
  <td align="right"><b>PvE:</b></td>
  <td><%= @card.pve %></td>
</tr>
<% if @related %>
<tr>
  <td align="right"><b>Related Card:</b></td>
  <td><%= link_to @related.name, :controller => "cards", :action => "show", :id => @related.id %></td>
</tr>
<% end %>
<% if @related2 %>
<tr>
  <td align="right"><b>Related Card:</b></td>
  <td><%= link_to @related2.name, :controller => "cards", :action => "show", :id => @related2.id %></td>
</tr>
<% end %>
<% if @related3 %>
<tr>
  <td align="right"><b>Related Card:</b></td>
  <td><%= link_to @related3.name, :controller => "cards", :action => "show", :id => @related3.id %></td>
</tr>
<% end %>
<% if @related4 %>
<tr>
  <td align="right"><b>Related Card:</b></td>
  <td><%= link_to @related4.name, :controller => "cards", :action => "show", :id => @related4.id %></td>
</tr>
<% end %>

</table>

<p>
	<b>Equipment:</b></p>
<table>	
<% @card.item.each do |item|%>
<tr>
<td><%= image_tag(item.image_main, :size=>"54x54") %></td>
<td valign="top"><%= link_to item.item_name, item %></td>
<td valign="top"><%= item.game_text %></td>
</tr>
<% end %>
</table>

</div>
</div>