config/routes.rb
Hex::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"  
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :socket_gems
  resources :champions
  resources :items
  resources :gear
  resources :pages
  resources :releases
  resources :traits
  resources :cards
  resources :users
  resources :sessions
  
  match '/links' => 'pages#show', :id => '2', :as => 'links'
  match '/cardexport' => 'cards#export'
  match '/itemexport' => 'items#export'
       

   root :to => 'pages#show', :id => '1'

end

app/models/card.rb
class Card < ActiveRecord::Base
#  COLOR = { "Artifact" => 0, "Blood" => 1, "Wild" => 2, "Diamond" => 3, "Ruby" => 4, "Sapphire" => 5 }
#  FACTION = { "None" => 0, "Ardent" => 1, "Underworld" => 2 }
#  RESTRICTION = { "None" => 0, "Unique" => 1 }
#  RARITY = { "None" => 0, "Common" => 1, "Uncommon" => 2, "Rare" => 3, "Legendary - PvE" => 4, "Legendary - PvP" => 5}
#  CARD_TYPE = { "Resource" => 0, "Constant" => 1, "Troop" => 2, "Basic Action" => 3, "Quick Action" => 4, "Artifact" => 5, "Artifact Troop" => 6}

#  def color
#    COLOR.key(read_attribute(:color))
#  end

#  def faction
#    FACTION.key(read_attribute(:faction))
#  end

#  def restriction
#    RESTRICTION.key(read_attribute(:restriction))
#  end

#  def rarity
#    RARITY.key(read_attribute(:rarity))
#  end

#  def card_type
#    CARD_TYPE.key(read_attribute(:card_type))
#  end
  
  def name_with_initial
    "#{name}"
  end

  def self.search(search)
    if search
      where('name LIKE ? OR traits LIKE ? OR game_text LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
  
  
  has_many :item
  belongs_to :release
  attr_accessible :related_card_id, :related_card2_id, :related_card3_id, :related_card4_id, :traits, :attack, :color, :cost, :defense, :faction, :game_text, :lore_text, :name, :number, :pve, :rarity, :restriction, :release_id, :threshold, :card_type, :image_main, :image_back, :image_alt_1
end

app/models/champion.rb
class Champion < ActiveRecord::Base
  POWER_TYPE = { "None" => 0, "Charge Power" => 1, "Passive Power" => 2, "Special Card" => 3, "Start of Game" => 4 }
  def power1_type
    POWER_TYPE.key(read_attribute(:power1_type))
  end
  def power2_type
    POWER_TYPE.key(read_attribute(:power2_type))
  end
  def power3_type
    POWER_TYPE.key(read_attribute(:power3_type))
  end
  def power4_type
    POWER_TYPE.key(read_attribute(:power4_type))
  end

  attr_accessible :name, :power1_game_text, :power1_name, :power1_type, :power1_unlock, :power2_game_text, :power2_name, :power2_type, :power2_unlock, :power3_game_text, :power3_name, :power3_type, :power3_unlock, :power4_game_text, :power4_name, :power4_type, :power4_unlock, :image_main, :source
end

app/models/item.rb
class Item < ActiveRecord::Base
  ITEM_TYPE = { "None" => 0, "Helmet" => 1, "Armor" => 2, "Glove" => 3, "Boots" => 4, "Weapon" => 5, "Trinket" => 6 }  
  RARITY = { "None" => 0, "Common" => 1, "Uncommon" => 2, "Rare" => 3, "Legendary" => 4}
  
 # def item_type
#    ITEM_TYPE.key(read_attribute(:item_type))
#  end
  def rarity
    RARITY.key(read_attribute(:rarity))
  end  

  def self.search(search)
    if search
      where('item_name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
      
  belongs_to :card
  attr_accessible :card_id, :game_text, :image_main, :item_type, :lore_text, :item_name, :rarity, :rulings, :set_card_id, :source
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description, :name, :rank, :url
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/release.rb
class Release < ActiveRecord::Base
  validates_uniqueness_of :release_name, :short_name
  
  def name_with_initial
    "#{release_name}"
  end

  has_many :card
  
  attr_accessible :release_name, :short_name, :release_date, :size
end

app/models/socket_gem.rb
class SocketGem < ActiveRecord::Base
  
  def name_with_initial
    "#{name}"
  end
    
      
  attr_accessible :gem_color, :game_text, :gem_name, :gem_type
end

app/models/trait.rb
class Trait < ActiveRecord::Base
  
  validates_uniqueness_of :trait_name
  
  def name_with_initial
    "#{trait_name}"
  end

  attr_accessible :trait_name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :email, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  # GET /champions
  # GET /champions.json
  def index
    @champions = Champion.order("name asc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @champions }
    end
  end

  # GET /champions/1
  # GET /champions/1.json
  def show
    @champion = Champion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @champion }
    end
  end

  # GET /champions/new
  # GET /champions/new.json
  def new
  if current_user
    @champion = Champion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @champion }
    end
  else
    redirect_to root_url
  end    
    
  end

  # GET /champions/1/edit
  def edit
    if current_user
    @champion = Champion.find(params[:id])
    else
      redirect_to root_url
    end    
  end

  # POST /champions
  # POST /champions.json
  def create
    @champion = Champion.new(params[:champion])

    respond_to do |format|
      if @champion.save
        format.html { redirect_to @champion, notice: 'Champion was successfully created.' }
        format.json { render json: @champion, status: :created, location: @champion }
      else
        format.html { render action: "new" }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /champions/1
  # PUT /champions/1.json
  def update
    @champion = Champion.find(params[:id])

    respond_to do |format|
      if @champion.update_attributes(params[:champion])
        format.html { redirect_to @champion, notice: 'Champion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champions/1
  # DELETE /champions/1.json
#  def destroy
#    @champion = Champion.find(params[:id])
#    @champion.destroy

#    respond_to do |format|
#      format.html { redirect_to champions_url }
#      format.json { head :no_content }
#    end
#  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def sortable(column, title = nil)
    title ||= column.titleize
    column = column == "trait.trait_name" ? "trait_name" : column
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc" 
    
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
    
  end
  
end

app/helpers/card_types_helper.rb
module CardTypesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/traits_helper.rb
module TraitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/champions/_form.html.erb
<%= form_for(@champion) do |f| %>
  <% if @champion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@champion.errors.count, "error") %> prohibited this champion from being saved:</h2>

      <ul>
      <% @champion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :power1_type %>
	<%= f.select :power1_type, { "None" => 0, "Charge Power" => 1, "Passive Power" => 2, "Special Card" => 3, "Start of Game" => 4 }%>	
    <%= f.label :power1_unlock %>
    <%= f.number_field :power1_unlock %>
  </div>
  <div class="field">
    <%= f.label :power1_game_text %><br />
    <%= f.text_area :power1_game_text, :size=>"80x5" %>
  </div>
  <div class="field">
    <%= f.label :power2_type %>
	<%= f.select :power2_type, { "None" => 0, "Charge Power" => 1, "Passive Power" => 2, "Special Card" => 3, "Start of Game" => 4 }%>	
    <%= f.label :power2_unlock %>
    <%= f.number_field :power2_unlock %>
  </div>
  <div class="field">
    <%= f.label :power2_game_text %><br />
    <%= f.text_area :power2_game_text, :size=>"80x5" %>
  </div>
  <div class="field">
  </div>
  <div class="field">
    <%= f.label :power3_type %>
	<%= f.select :power3_type, { "None" => 0, "Charge Power" => 1, "Passive Power" => 2, "Special Card" => 3, "Start of Game" => 4 }%>	
    <%= f.label :power3_unlock %>
    <%= f.number_field :power3_unlock %>
  </div>
  <div class="field">
    <%= f.label :power3_game_text %><br />
    <%= f.text_area :power3_game_text, :size=>"80x5" %>
  </div>
  <div class="field">
    <%= f.label :power4_type %>
	<%= f.select :power4_type, { "None" => 0, "Charge Power" => 1, "Passive Power" => 2, "Special Card" => 3, "Start of Game" => 4 }%>	
    <%= f.label :power4_unlock %>
    <%= f.number_field :power4_unlock %>
	
  </div>
  <div class="field">
    <%= f.label :power4_game_text %><br />
    <%= f.text_area :power4_game_text, :size=>"80x5" %>
  </div>
  <div class="field">
    <%= f.label :image_main %>
    <%= f.text_field :image_main %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/champions/edit.html.erb
<h1>Editing champion</h1>

<%= render 'form' %>

<%= link_to 'Show', @champion %> |
<%= link_to 'Back', champions_path %>

app/views/champions/index.html.erb
<% if current_user %>
<%= link_to 'New Champion', new_champion_path %>
<% end %>


<h1>CHAMPIONS</h1>

<table width="980" class="pretty">
  <tr>
    <th width="20%">Name</th>
    <th width="20%">Power 1</th>
    <th width="20%">Power 2</th>
    <th width="20%">Power 3</th>
    <th width="20%">Power 4</th>
  </tr>

<% @champions.each do |champion| %>
  <tr class="<%= cycle("odd", "even") %>">	  
    <td valign="top"><%= link_to champion.name, champion %></td>
    <td valign="top"><b><%= champion.power1_type %></b><br><%= champion.power1_game_text %></td>
    <td valign="top"><b><%= champion.power2_type %></b><br><%= champion.power2_game_text %></td>
    <td valign="top"><b><%= champion.power3_type %></b><br><%= champion.power3_game_text %></td>
    <td valign="top"><b><%= champion.power4_type %></b><br><%= champion.power4_game_text %></td>
  </tr>
<% end %>
</table>

<br />

app/views/champions/new.html.erb
<h1>New champion</h1>

<%= render 'form' %>

<%= link_to 'Back', champions_path %>

app/views/champions/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
<%= link_to 'Edit', edit_champion_path(@champion) %> |
<%= link_to 'New Champion', new_champion_path %>
<% end %>


<div id="champion-body">
<div id="champion-image">	
<%= image_tag(@champion.image_main) %>
</div>
<div id="champion-content">
<h1><%= @champion.name %></h1>

<p>
  <b><%= @champion.power1_type.upcase %><br></b>
  <b>UNLOCKED AT LEVEL <%= @champion.power1_unlock %></b><br>
  <%= @champion.power1_game_text %>
</p>

<p>
  <b><%= @champion.power2_type.upcase %><br></b>
  <b>UNLOCKED AT LEVEL <%= @champion.power2_unlock %></b><br>
  <%= @champion.power2_game_text %>
</p>
<p>
  <b><%= @champion.power2_type.upcase %><br></b>
  <b>UNLOCKED AT LEVEL <%= @champion.power2_unlock %></b><br>
  <%= @champion.power3_game_text %>
</p>
<p>
  <b><%= @champion.power4_type.upcase %><br></b>
  <b>UNLOCKED AT LEVEL <%= @champion.power4_unlock %></b><br>
  <%= @champion.power4_game_text %>
</p>
</div>
</div>