config/routes.rb
Hex::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"  
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :socket_gems
  resources :champions
  resources :items
  resources :gear
  resources :pages
  resources :releases
  resources :traits
  resources :cards
  resources :users
  resources :sessions
  
  match '/links' => 'pages#show', :id => '2', :as => 'links'
  match '/cardexport' => 'cards#export'
  match '/itemexport' => 'items#export'
       

   root :to => 'pages#show', :id => '1'

end

app/models/card.rb
class Card < ActiveRecord::Base
#  COLOR = { "Artifact" => 0, "Blood" => 1, "Wild" => 2, "Diamond" => 3, "Ruby" => 4, "Sapphire" => 5 }
#  FACTION = { "None" => 0, "Ardent" => 1, "Underworld" => 2 }
#  RESTRICTION = { "None" => 0, "Unique" => 1 }
#  RARITY = { "None" => 0, "Common" => 1, "Uncommon" => 2, "Rare" => 3, "Legendary - PvE" => 4, "Legendary - PvP" => 5}
#  CARD_TYPE = { "Resource" => 0, "Constant" => 1, "Troop" => 2, "Basic Action" => 3, "Quick Action" => 4, "Artifact" => 5, "Artifact Troop" => 6}

#  def color
#    COLOR.key(read_attribute(:color))
#  end

#  def faction
#    FACTION.key(read_attribute(:faction))
#  end

#  def restriction
#    RESTRICTION.key(read_attribute(:restriction))
#  end

#  def rarity
#    RARITY.key(read_attribute(:rarity))
#  end

#  def card_type
#    CARD_TYPE.key(read_attribute(:card_type))
#  end
  
  def name_with_initial
    "#{name}"
  end

  def self.search(search)
    if search
      where('name LIKE ? OR traits LIKE ? OR game_text LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
  
  
  has_many :item
  belongs_to :release
  attr_accessible :related_card_id, :related_card2_id, :related_card3_id, :related_card4_id, :traits, :attack, :color, :cost, :defense, :faction, :game_text, :lore_text, :name, :number, :pve, :rarity, :restriction, :release_id, :threshold, :card_type, :image_main, :image_back, :image_alt_1
end

app/models/champion.rb
class Champion < ActiveRecord::Base
  POWER_TYPE = { "None" => 0, "Charge Power" => 1, "Passive Power" => 2, "Special Card" => 3, "Start of Game" => 4 }
  def power1_type
    POWER_TYPE.key(read_attribute(:power1_type))
  end
  def power2_type
    POWER_TYPE.key(read_attribute(:power2_type))
  end
  def power3_type
    POWER_TYPE.key(read_attribute(:power3_type))
  end
  def power4_type
    POWER_TYPE.key(read_attribute(:power4_type))
  end

  attr_accessible :name, :power1_game_text, :power1_name, :power1_type, :power1_unlock, :power2_game_text, :power2_name, :power2_type, :power2_unlock, :power3_game_text, :power3_name, :power3_type, :power3_unlock, :power4_game_text, :power4_name, :power4_type, :power4_unlock, :image_main, :source
end

app/models/item.rb
class Item < ActiveRecord::Base
  ITEM_TYPE = { "None" => 0, "Helmet" => 1, "Armor" => 2, "Glove" => 3, "Boots" => 4, "Weapon" => 5, "Trinket" => 6 }  
  RARITY = { "None" => 0, "Common" => 1, "Uncommon" => 2, "Rare" => 3, "Legendary" => 4}
  
 # def item_type
#    ITEM_TYPE.key(read_attribute(:item_type))
#  end
  def rarity
    RARITY.key(read_attribute(:rarity))
  end  

  def self.search(search)
    if search
      where('item_name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
      
  belongs_to :card
  attr_accessible :card_id, :game_text, :image_main, :item_type, :lore_text, :item_name, :rarity, :rulings, :set_card_id, :source
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description, :name, :rank, :url
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/release.rb
class Release < ActiveRecord::Base
  validates_uniqueness_of :release_name, :short_name
  
  def name_with_initial
    "#{release_name}"
  end

  has_many :card
  
  attr_accessible :release_name, :short_name, :release_date, :size
end

app/models/socket_gem.rb
class SocketGem < ActiveRecord::Base
  
  def name_with_initial
    "#{name}"
  end
    
      
  attr_accessible :gem_color, :game_text, :gem_name, :gem_type
end

app/models/trait.rb
class Trait < ActiveRecord::Base
  
  validates_uniqueness_of :trait_name
  
  def name_with_initial
    "#{trait_name}"
  end

  attr_accessible :trait_name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :email, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/traits_helper.rb
module TraitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hex</title>
  <link href='http://fonts.googleapis.com/css?family=Archivo+Black' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag :defaults%>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="header"><%= link_to 'HEXMMO.COM', '/', :class => 'headerlink' %> | <%= link_to 'CARDS', cards_path, :class => 'headerlink' %> | <%= link_to 'GEAR', items_path, :class => 'headerlink' %> | <%= link_to 'CHAMPIONS', champions_path, :class => 'headerlink' %> | <%= link_to 'GEMS', socket_gems_path, :class => 'headerlink' %> | <%= link_to 'LINKS', links_path, :class => 'headerlink'%></div>	
<div id="user_nav">
	<% if current_user %>
	Logged in as: <%= current_user.email %> - 
	<%= link_to "Log out", log_out_path %>
	<% end %>

</div>

<%= yield %>



<div id="footer"> </div>	
<div id="disclaimer">This website is neither owned nor operated by Cryptozoic Entertainment. We do not claim ownership over the images, videos, or articles published here. All trademarks and copyrights belong to their respective owners, and are used here under the terms of Fair Use. No copyright infringement is intended. </div>


</body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41074265-1', 'hexmmo.com');
  ga('send', 'pageview');

</script>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.body %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'New Page', new_page_path %>
<% end %>
<div id="page-body">
<div id="page-content">	
<h1><%= @page.title %></h1>

<p><%= @page.body.html_safe %></p>
</div>
</div>